export default [
  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/1.png",
  },

  {
    Duration: "Monthly",
    PkgName: "SUPER DUPER",
    DataFor: "8 GB",
    JazzMins: "3000",
    OtherNetworkMins: "165",
    SMS: "3000",
    Charges: "Rs.655",
    img: "/images/2.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/3.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/4.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/5.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/6.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/1.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/2.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/3.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/4.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/5.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/6.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/1.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/2.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/3.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/4.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/5.png",
  },

  {
    Duration: "WEEKLY",
    PkgName: "SOCIAL PLUS",
    DataFor: "8 GB",
    JazzMins: "500",
    OtherNetworkMins: "25",
    SMS: "500",
    Charges: "Rs.170",
    img: "/images/6.png",
  },
];
